theme: minima

title: Esprit
excerpt: Essays on thought and experience
description: 精神病理学、哲学、人文学を手がかりに、こころの体験の成り立ちを考える個人サイトです。
url: "https://tortoise-esprit.com"
baseurl: ""
lang: ja-JP
author: Esprit

timezone: Asia/Tokyo

google_analytics: "G-EPMW3T3Q0K"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/page:num"

image: "/assets/ogp/ogp-default.png"

header_pages:
  - about.md
  - glossary/index.md
  - fragments.md
  - contact.md
  - privacy.md
